"""Expected clustering for each dataset at k=3.

Generated by tools/answers.py — best of 40 k-means++ restarts, so these are the
global optima rather than one run's local minimum. Regenerate with:

    uv run python tools/answers.py --write-solutions
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from interview_k.show import Centroid

K = 3

CENTROIDS: dict[str, list[Centroid]] = {
    "TWENTY": [
        (11.857142857142858, 18.285714285714285),
        (48.142857142857146, 78.85714285714286),
        (82.66666666666667, 30.5),
    ],
    "BLOBS": [
        (20.11377245508982, 19.94610778443114),
        (50.15615615615616, 80.43843843843844),
        (79.86786786786787, 29.91891891891892),
    ],
    "TIGHT": [
        (-0.10179640718562874, 3.0),
        (-0.015060240963855422, -0.05421686746987952),
        (3.0508982035928143, 2.9820359281437128),
    ],
    "LOPSIDED": [
        (19.694285714285716, 19.865714285714287),
        (20.36, 70.36),
        (60.096, 60.104),
    ],
    "ELONGATED": [
        (6.074550128534704, 38.5706940874036),
        (40.022222222222226, 55.025396825396825),
        (51.16216216216216, 25.95608108108108),
    ],
    "UNSCALED": [
        (4.881974248927039, 5067.8669527897),
        (5.003378378378378, 3925.625),
        (5.23109243697479, 6087.672268907563),
    ],
    "UNIFORM": [
        (14.0, 17.90909090909091),
        (45.30612244897959, 79.6734693877551),
        (70.575, 30.2),
    ],
}

SIZES: dict[str, list[int]] = {
    "TWENTY": [7, 7, 6],
    "BLOBS": [334, 333, 333],
    "TIGHT": [334, 332, 334],
    "LOPSIDED": [700, 50, 250],
    "ELONGATED": [389, 315, 296],
    "UNSCALED": [466, 296, 238],
    "UNIFORM": [11, 49, 40],
}

INERTIA: dict[str, float] = {
    "TWENTY": 344.8333333333333,
    "BLOBS": 32415.571451691212,
    "TIGHT": 816.5146634441959,
    "LOPSIDED": 54295.98628571429,
    "ELONGATED": 353221.43049898045,
    "UNSCALED": 136776381.35816902,
    "UNIFORM": 55882.26776437848,
}
