/**
 * The port is only a port if it renders what Python renders. `parity.json` is generated by
 * `py/tools/ts_fixture.py`; a failure here means show() drifted from the original.
 *
 * The datasets themselves are no longer compared: both languages read the same
 * datasets.json, so there is nothing left to disagree about.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { DATASETS, TWENTY } from "./datasets.ts";
import { show, type Centroid, type Point } from "../../../ts/src/dataviz.ts";
import { capture } from "../../../ts/test/capture.ts";

interface Fixture {
  renders: Record<string, string>;
}

const fixture: Fixture = JSON.parse(readFileSync(new URL("./parity.json", import.meta.url), "utf8"));



const SQUARE: Point[] = [
  [0, 0],
  [0, 1],
  [1, 0],
  [1, 1],
];
const HALF: Centroid[] = [
  [0, 0.5],
  [1, 0.5],
];

const renders: Record<string, () => void> = {
  twenty: () => show({ points: TWENTY, width: 40, height: 12, title: "twenty" }),
  two_groups: () => show([SQUARE.slice(0, 2), SQUARE.slice(2)], HALF, { width: 20, height: 5 }),
  nan_centroid: () => show([SQUARE], [[NaN, 0]], { width: 20, height: 5 }),
  empty: () => show([], undefined, { width: 20, height: 5 }),
  identical: () => show({ points: Array.from({ length: 5 }, () => [2, 2] as Point), width: 20, height: 5 }),
  blobs: () => show({ points: DATASETS.BLOBS!, width: 60, height: 16, title: "blobs" }),
};

for (const [name, draw] of Object.entries(renders)) {
  test(`render ${name} is byte-identical to Python`, () => {
    assert.equal(capture(draw), fixture.renders[name]);
  });
}
