"""Emit the parity fixture the TypeScript port is tested against.

    mise run sync kmeans   # writes questions/kmeans/ts/parity.json

The TS port only earns the name if it produces the same points and the same picture, so
the check is a digest of every dataset plus the literal stdout of a few show() calls. It
also carries the answer key, which is what holds `ts/main.ts` to the same clusters Python
reaches rather than merely to a converged answer of its own.

Regenerated by this question's sync.py, after solutions.py — a TS test failure afterwards
means the port drifted, not that the fixture is stale.
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import json
from pathlib import Path
from typing import TYPE_CHECKING, TypedDict

if TYPE_CHECKING:
    from collections.abc import Callable

from interview_k.dataviz import Centroid, Point, show

QUESTION = Path(__file__).parent.parent
BUILD = QUESTION.parent.parent / "build" / QUESTION.name
FIXTURE = BUILD / "parity.json"

DATASETS: dict[str, list[Point]] = {
    name: [(x, y) for x, y in points] for name, points in json.loads((QUESTION / "common" / "data.json").read_text()).items()
}
TWENTY = DATASETS["TWENTY"]

SQUARE: list[Point] = [(0, 0), (0, 1), (1, 0), (1, 1)]


# The wire shape, declared once so the TS-side `interface Fixture` has something to match.
class AnswerFixture(TypedDict):
    """What the TS side is held to: the reference optimum's cost, not its exact partition.

    The two languages seed k-means++ from different generators now that the datasets are
    read rather than regenerated, so they reach equally valid local minima. Inertia is the
    thing that is actually claimed — "as good as the key" — and it compares across both.
    """

    inertia: float
    centroids: list[list[float]]


class Fixture(TypedDict):
    renders: dict[str, str]
    k: int
    answers: dict[str, AnswerFixture]


def digest(points: list[Point]) -> str:
    return hashlib.sha256(";".join(f"{x},{y}" for x, y in points).encode()).hexdigest()


def normalised(clusters: list[tuple[Centroid, list[Point]]]) -> list[tuple[Centroid, list[Point]]]:
    """Sort points inside each cluster, then clusters by their points. Ordering is not graded.

    Points are pairs, so ordering groups by their flattened coordinates is the same order
    Python's tuple comparison gives — and one a JS comparator can reproduce exactly.
    """
    return sorted(((centroid, sorted(points)) for centroid, points in clusters), key=lambda pair: [v for p in pair[1] for v in p])


def rendered(draw: Callable[[], None]) -> str:
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        draw()
    return buffer.getvalue()


def main() -> int:
    solutions = json.loads((BUILD / "solutions.json").read_text())
    # Same normalisation test_solutions.py applies: ordering is not part of the contract.
    answers: dict[str, AnswerFixture] = {}
    for name, clusters in solutions["ANSWERS"].items():
        groups = normalised([((cx, cy), [(x, y) for x, y in pts]) for (cx, cy), pts in clusters])
        answers[name] = {
            "inertia": sum((x - cx) ** 2 + (y - cy) ** 2 for (cx, cy), points in groups for x, y in points),
            "centroids": [[centroid[0], centroid[1]] for centroid, _ in groups],
        }
    fixture: Fixture = {
        "renders": {
            "twenty": rendered(lambda: show(points=TWENTY, width=40, height=12, title="twenty")),
            "two_groups": rendered(lambda: show([SQUARE[:2], SQUARE[2:]], [(0.0, 0.5), (1.0, 0.5)], width=20, height=5)),
            "nan_centroid": rendered(lambda: show([SQUARE], [(float("nan"), 0.0)], width=20, height=5)),
            "empty": rendered(lambda: show([], width=20, height=5)),
            "identical": rendered(lambda: show(points=[(2, 2)] * 5, width=20, height=5)),
            "blobs": rendered(lambda: show(points=DATASETS["BLOBS"], width=60, height=16, title="blobs")),
        },
        "k": solutions["K"],
        "answers": answers,
    }

    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {FIXTURE} — {len(fixture['renders'])} renders, {len(fixture['answers'])} answers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
