/**
 * The port is only a port if it agrees with Python. `parity.json` is generated by
 * `py/tools/ts_fixture.py`; a failure here means the TS side drifted from the original.
 */

import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test from "node:test";

import { DATASETS, TWENTY } from "../src/data.ts";
import { show, type Centroid, type Point } from "../src/show.ts";
import { capture } from "./capture.ts";

interface Fixture {
  datasets: Record<string, { n: number; first: [number, number]; last: [number, number]; sha256: string }>;
  renders: Record<string, string>;
}

const fixture: Fixture = JSON.parse(readFileSync(new URL("./parity.json", import.meta.url), "utf8"));
const all: Record<string, Point[]> = { twenty: TWENTY, ...DATASETS };

const digest = (points: Point[]): string =>
  createHash("sha256")
    .update(points.map(([x, y]) => `${x},${y}`).join(";"))
    .digest("hex");

for (const [name, expected] of Object.entries(fixture.datasets)) {
  test(`dataset ${name} matches Python point for point`, () => {
    const points = all[name]!;
    assert.equal(points.length, expected.n);
    assert.deepEqual(points[0], expected.first);
    assert.deepEqual(points.at(-1), expected.last);
    assert.equal(digest(points), expected.sha256);
  });
}

const SQUARE: Point[] = [
  [0, 0],
  [0, 1],
  [1, 0],
  [1, 1],
];
const HALF: Centroid[] = [
  [0, 0.5],
  [1, 0.5],
];

const renders: Record<string, () => void> = {
  twenty: () => show({ points: TWENTY, width: 40, height: 12, title: "twenty" }),
  two_groups: () => show([SQUARE.slice(0, 2), SQUARE.slice(2)], HALF, { width: 20, height: 5 }),
  nan_centroid: () => show([SQUARE], [[NaN, 0]], { width: 20, height: 5 }),
  empty: () => show([], undefined, { width: 20, height: 5 }),
  identical: () => show({ points: Array.from({ length: 5 }, () => [2, 2] as Point), width: 20, height: 5 }),
  blobs: () => show({ points: DATASETS.blobs!, width: 60, height: 16, title: "blobs" }),
};

for (const [name, draw] of Object.entries(renders)) {
  test(`render ${name} is byte-identical to Python`, () => {
    assert.equal(capture(draw), fixture.renders[name]);
  });
}
