/**
 * The datasets, read from the JSON both languages share, plus the plotting helpers.
 *
 * `datasets.json` is generated by `py/tools/datasets.py` (`mise run datasets`) — the points
 * are not regenerated here, which is why this port no longer carries a copy of CPython's
 * Mersenne Twister just to agree with Python about `gauss()`.
 */

import { readFileSync } from "node:fs";

import type { Point } from "./dataviz.ts";

// Read, not imported: a JSON import needs an attribute node insists on and ts-node rejects.
const datasets = JSON.parse(readFileSync(new URL("../../datasets.json", import.meta.url), "utf8")) as Record<string, number[][]>;

export { MARKS, printClusters, show } from "./dataviz.ts";
export type { Centroid, Cluster, Point, ShowBox, ShowSpec } from "./dataviz.ts";

export const DATASETS: Record<string, Point[]> = Object.fromEntries(
  Object.entries(datasets).map(([name, points]) => [name, points.map(([x, y]) => [x!, y!] as Point)]),
);

export const { TWENTY, BLOBS, TIGHT, LOPSIDED, ELONGATED, UNSCALED, UNIFORM } = DATASETS as Record<string, Point[]> & {
  TWENTY: Point[];
  BLOBS: Point[];
  TIGHT: Point[];
  LOPSIDED: Point[];
  ELONGATED: Point[];
  UNSCALED: Point[];
  UNIFORM: Point[];
};
